package com.epam.jwt.task5.controller;

public enum ServiceWordsKey {
    SUBMIT,
    DISPLAY,
    LOGOUT,
    CHANGE_LANGUAGE,
    RUSSIAN,
    ENGLISH,
    E_MAIL,
    PASSWORD,
    SIGN_IN,
    SIGN_UP,
    NAME,
    BACK,

    COURSE_NAME,
    COURSE_DESCRIPTION,
    PLANNED_COURSES_LABEL,
    ACTIVE_COURSES_LABEL,
    COMPLETED_COURSES_LABEL,
    COURSE_OF_TEACHER,
    STUDENT_COURSES,

    TEACHERS,
    TEACHER,
    TEACHER_NAME,

    REQUESTS_TO_REGISTRATION,
    REQUESTS_TO_COMPLETE_COURSE,
    SEND_REQUEST,
    REJECT,

    SUBJECT,

    STUDENT,
    STUDENT_REVIEW,
    STUDENTS,
    STUDENT_NAME,
    STUDENT_EMAIL,

    TASKS,
    TASK_NAME,
    DEADLINE,
    ASSIGNMENT_DATE,

    SOLUTIONS,
    MARK,
    ANSWER,

    REVIEW_DESCRIPTION,
    CHANGE_COURSE_STATUS,
    END_COURSE,
    ADD_COURSE,
    ADD_REVIEW,
    ADD_TASK,
    ADD_TEACHER,
    COURSE_DATA,
    SOLUTION,
    MAIN

}
