package com.epam.jwt.task5.service.validator;

public interface ValidationMessageKey {

    String USER_EXISTS_MESSAGE = "USER_EXISTS_MESSAGE";
    String NOT_VALID_NAME_MESSAGE = "NOT_VALID_NAME_MESSAGE";
    String NOT_VALID_DESCRIPTION_MESSAGE = "NOT_VALID_DESCRIPTION_MESSAGE";
    String NOT_VALID_EMAIL_MESSAGE = "NOT_VALID_EMAIL_MESSAGE";
    String NOT_VALID_PASSWORD_MESSAGE = "NOT_VALID_PASSWORD_MESSAGE";
    String HACKER_HELLO_MESSAGE = "HACKER_HELLO_MESSAGE";
    String INVALID_MARK_MESSAGE = "INVALID_MARK_MESSAGE";
    String INVALID_ANSWER_MESSAGE = "INVALID_ANSWER_MESSAGE";
    String INVALID_DATE_FORMAT_MESSAGE = "INVALID_DATE_FORMAT_MESSAGE";
}
